/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;


/**
 *
 * @author sapat
 */
public class SignUp_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Splash_GUI
     */
    public SignUp_GUI() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        showPassword_btn = new javax.swing.JToggleButton();
        goBack_btn1 = new javax.swing.JButton();
        goBack_btn = new javax.swing.JButton();
        password_txt = new javax.swing.JPasswordField();
        email_txt = new javax.swing.JTextField();
        phoneNumber_txt = new javax.swing.JTextField();
        name_txt = new javax.swing.JTextField();
        cpf_txt = new javax.swing.JTextField();
        send_btn = new javax.swing.JButton();
        exit_btn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        showPassword_btn.setBackground(new java.awt.Color(255, 255, 255));
        showPassword_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/eyeIcon.png"))); // NOI18N
        showPassword_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPassword_btnActionPerformed(evt);
            }
        });
        jPanel1.add(showPassword_btn);
        showPassword_btn.setBounds(300, 290, 60, 30);

        goBack_btn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        goBack_btn1.setText("Já tenho cadastro");
        goBack_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBack_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(goBack_btn1);
        goBack_btn1.setBounds(40, 380, 320, 20);

        goBack_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        goBack_btn.setText("VOLTAR");
        goBack_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBack_btnActionPerformed(evt);
            }
        });
        jPanel1.add(goBack_btn);
        goBack_btn.setBounds(260, 620, 130, 30);

        password_txt.setText("jPasswordField1");
        jPanel1.add(password_txt);
        password_txt.setBounds(150, 290, 150, 30);

        email_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        email_txt.setText("Insira seu email");
        jPanel1.add(email_txt);
        email_txt.setBounds(150, 220, 210, 30);

        phoneNumber_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        phoneNumber_txt.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        phoneNumber_txt.setText("Insira seu numero de telefone");
        jPanel1.add(phoneNumber_txt);
        phoneNumber_txt.setBounds(190, 160, 170, 30);

        name_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        name_txt.setText("Insira seu nome completo");
        jPanel1.add(name_txt);
        name_txt.setBounds(150, 100, 210, 30);

        cpf_txt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cpf_txt.setText("Insira seu CPF");
        jPanel1.add(cpf_txt);
        cpf_txt.setBounds(150, 40, 210, 30);

        send_btn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        send_btn.setText("ENVIAR");
        jPanel1.add(send_btn);
        send_btn.setBounds(40, 330, 320, 40);

        exit_btn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        exit_btn1.setText("SAIR");
        exit_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btn1ActionPerformed(evt);
            }
        });
        jPanel1.add(exit_btn1);
        exit_btn1.setBounds(260, 660, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/PowerHub_SignUp.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 704);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(396, 704));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void goBack_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBack_btn1ActionPerformed
        Model.Funcs_DAO.changeScreen(this, new Login_GUI());
    }//GEN-LAST:event_goBack_btn1ActionPerformed

    private void goBack_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBack_btnActionPerformed
        Model.Funcs_DAO.changeScreen(this, new Login_GUI());
    }//GEN-LAST:event_goBack_btnActionPerformed

    private void exit_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btn1ActionPerformed
        Model.Funcs_DAO.exit();
    }//GEN-LAST:event_exit_btn1ActionPerformed

    private void showPassword_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPassword_btnActionPerformed
        if (showPassword_btn.isSelected()) {
            // Mostrar os caracteres reais
            password_txt.setEchoChar('\0');
        } else {
            // Ocultar os caracteres reais
            password_txt.setEchoChar('\u25cf');
        }
    }//GEN-LAST:event_showPassword_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SignUp_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField cpf_txt;
    public static javax.swing.JTextField email_txt;
    private javax.swing.JButton exit_btn1;
    private javax.swing.JButton goBack_btn;
    private javax.swing.JButton goBack_btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField name_txt;
    public static javax.swing.JPasswordField password_txt;
    public static javax.swing.JTextField phoneNumber_txt;
    private javax.swing.JButton send_btn;
    private javax.swing.JToggleButton showPassword_btn;
    // End of variables declaration//GEN-END:variables
}
